/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package form;
import crud.crud;
import javax.swing.JOptionPane;


/**
 *
 * @author Aiman
 */
public class FrameApp extends javax.swing.JFrame {
    crud mycode;

    /**
     * Creates new form FrameApp
     */
    public FrameApp() {
        initComponents();
        this.setLocationRelativeTo(null);
        mycode = new crud();
        mycode.tampilDataToko(tabelToko, "SELECT*FROM toko");
        mycode.tampilDataTransaksi(tabelTransaksi, "SELECT*FROM transaksi");
        mycode.tampilDataProduk(tabelProduk, "SELECT*FROM produk");
        mycode.tampilDataKurir(tabelKurir, "SELECT*FROM kurir");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlProduk = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtNamaProduk = new javax.swing.JTextField();
        txtIdProduk = new javax.swing.JTextField();
        txtDeskripsi = new javax.swing.JTextField();
        btnHpsProduk = new javax.swing.JButton();
        btnSmpnProduk = new javax.swing.JButton();
        btnUbhPO = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtHrgProduk = new javax.swing.JTextField();
        txtKategori = new javax.swing.JTextField();
        txtBerat = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        txtCariProduk = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelProduk = new javax.swing.JTable();
        btnCetakProduk = new javax.swing.JButton();
        pnlToko = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNamaToko = new javax.swing.JTextField();
        txtIdToko = new javax.swing.JTextField();
        txtTlpToko = new javax.swing.JTextField();
        txtAlamatToko = new javax.swing.JTextField();
        txtCariToko = new javax.swing.JTextField();
        txtRatingToko = new javax.swing.JTextField();
        btnHpsToko = new javax.swing.JButton();
        btnSmpnToko = new javax.swing.JButton();
        btnUbhToko = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelToko = new javax.swing.JTable();
        txtProdukRelasi = new javax.swing.JTextField();
        btnCetakToko = new javax.swing.JButton();
        pnlTransaksi = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtInvoice = new javax.swing.JTextField();
        txtIdTransaksi = new javax.swing.JTextField();
        txtJlhTotal = new javax.swing.JTextField();
        txtTglBeli = new javax.swing.JTextField();
        txtCariTransaksi = new javax.swing.JTextField();
        btnHpsTransaksi = new javax.swing.JButton();
        btnSmpnTransaksi = new javax.swing.JButton();
        btnUbhBrg = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtNamaTokoTrans = new javax.swing.JTextField();
        txtNamaProdukTrans = new javax.swing.JTextField();
        txtHargaTrans = new javax.swing.JTextField();
        txtJlhProdukTrans = new javax.swing.JTextField();
        txtTotalHarga = new javax.swing.JTextField();
        txtKodeKurirTrans = new javax.swing.JTextField();
        txtOngkosKirimTrans = new javax.swing.JTextField();
        btnCetakTransaksi = new javax.swing.JButton();
        pnlKurir = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtNamaKurir = new javax.swing.JTextField();
        txtIdKurir = new javax.swing.JTextField();
        txtOngkosKirim = new javax.swing.JTextField();
        txtKodeKurir = new javax.swing.JTextField();
        txtCariKurir = new javax.swing.JTextField();
        btnHpsKurir = new javax.swing.JButton();
        btnSmpnKurir = new javax.swing.JButton();
        btnUbhKurir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelKurir = new javax.swing.JTable();
        btnCetakKurir = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnToko = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnProduk = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnKurir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content.setBackground(new java.awt.Color(153, 204, 255));
        Content.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(204, 204, 204));
        pnlHome.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        Content.add(pnlHome, "card6");

        pnlProduk.setBackground(new java.awt.Color(204, 204, 204));
        pnlProduk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Deskripsi");
        pnlProduk.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Nama Produk");
        pnlProduk.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("ID Produk");
        pnlProduk.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        pnlProduk.add(txtNamaProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 220, -1));
        pnlProduk.add(txtIdProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 220, -1));
        pnlProduk.add(txtDeskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 220, -1));

        btnHpsProduk.setText("HAPUS");
        btnHpsProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsProdukActionPerformed(evt);
            }
        });
        pnlProduk.add(btnHpsProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 90, -1));

        btnSmpnProduk.setText("SIMPAN");
        btnSmpnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnProdukActionPerformed(evt);
            }
        });
        pnlProduk.add(btnSmpnProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 90, -1));

        btnUbhPO.setText("UBAH");
        btnUbhPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhPOActionPerformed(evt);
            }
        });
        pnlProduk.add(btnUbhPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 90, -1));

        jLabel22.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Berat");
        pnlProduk.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Harga");
        pnlProduk.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Kategori");
        pnlProduk.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        pnlProduk.add(txtHrgProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 220, -1));
        pnlProduk.add(txtKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 220, -1));
        pnlProduk.add(txtBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 220, -1));

        jLabel25.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Stok");
        pnlProduk.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        pnlProduk.add(txtStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 220, -1));

        txtCariProduk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariProdukKeyReleased(evt);
            }
        });
        pnlProduk.add(txtCariProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 355, -1));

        tabelProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelProdukMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelProduk);

        pnlProduk.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 490, 181));

        btnCetakProduk.setText("CETAK");
        btnCetakProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakProdukActionPerformed(evt);
            }
        });
        pnlProduk.add(btnCetakProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 90, -1));

        Content.add(pnlProduk, "card4");

        pnlToko.setBackground(new java.awt.Color(204, 204, 204));
        pnlToko.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Produk");
        pnlToko.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Rating");
        pnlToko.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Telpon");
        pnlToko.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Alamat Toko");
        pnlToko.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama Toko");
        pnlToko.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID Toko");
        pnlToko.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        pnlToko.add(txtNamaToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 220, -1));
        pnlToko.add(txtIdToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 220, -1));
        pnlToko.add(txtTlpToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 220, -1));
        pnlToko.add(txtAlamatToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 220, -1));

        txtCariToko.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariTokoKeyReleased(evt);
            }
        });
        pnlToko.add(txtCariToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 340, -1));
        pnlToko.add(txtRatingToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 220, -1));

        btnHpsToko.setText("HAPUS");
        btnHpsToko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsTokoActionPerformed(evt);
            }
        });
        pnlToko.add(btnHpsToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 90, -1));

        btnSmpnToko.setText("SIMPAN");
        btnSmpnToko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnTokoActionPerformed(evt);
            }
        });
        pnlToko.add(btnSmpnToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 90, -1));

        btnUbhToko.setText("UBAH");
        btnUbhToko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhTokoActionPerformed(evt);
            }
        });
        pnlToko.add(btnUbhToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 90, -1));

        tabelToko.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelToko.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTokoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelToko);

        pnlToko.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 310, 460, 129));

        txtProdukRelasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdukRelasiActionPerformed(evt);
            }
        });
        pnlToko.add(txtProdukRelasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 220, -1));

        btnCetakToko.setText("CETAK");
        btnCetakToko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakTokoActionPerformed(evt);
            }
        });
        pnlToko.add(btnCetakToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 90, -1));

        Content.add(pnlToko, "card3");

        pnlTransaksi.setBackground(new java.awt.Color(204, 204, 204));
        pnlTransaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nama Toko");
        pnlTransaksi.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Tanggal Beli");
        pnlTransaksi.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("ID Transaksi");
        pnlTransaksi.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        pnlTransaksi.add(txtInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 220, -1));
        pnlTransaksi.add(txtIdTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 220, -1));
        pnlTransaksi.add(txtJlhTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 220, -1));
        pnlTransaksi.add(txtTglBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 220, -1));

        txtCariTransaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariTransaksiKeyReleased(evt);
            }
        });
        pnlTransaksi.add(txtCariTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 380, -1));

        btnHpsTransaksi.setText("HAPUS");
        btnHpsTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsTransaksiActionPerformed(evt);
            }
        });
        pnlTransaksi.add(btnHpsTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, 100, -1));

        btnSmpnTransaksi.setText("SIMPAN");
        btnSmpnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnTransaksiActionPerformed(evt);
            }
        });
        pnlTransaksi.add(btnSmpnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 100, -1));

        btnUbhBrg.setText("UBAH");
        btnUbhBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhBrgActionPerformed(evt);
            }
        });
        pnlTransaksi.add(btnUbhBrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, 100, -1));

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTransaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelTransaksi);

        pnlTransaksi.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 790, 180));

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Nama Produk");
        pnlTransaksi.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel28.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Invoice");
        pnlTransaksi.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 65, -1));

        jLabel29.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Harga");
        pnlTransaksi.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 65, 20));

        jLabel30.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Jumlah Produk");
        pnlTransaksi.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 130, 20));

        jLabel31.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Total Harga");
        pnlTransaksi.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 120, 20));

        jLabel32.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Kode Kurir");
        pnlTransaksi.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 120, 20));

        jLabel33.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Ongkos Kirim");
        pnlTransaksi.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 120, 20));

        jLabel34.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Jumlah Total");
        pnlTransaksi.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 120, 20));
        pnlTransaksi.add(txtNamaTokoTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 220, -1));
        pnlTransaksi.add(txtNamaProdukTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 220, -1));
        pnlTransaksi.add(txtHargaTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 220, -1));
        pnlTransaksi.add(txtJlhProdukTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 220, -1));
        pnlTransaksi.add(txtTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 220, -1));
        pnlTransaksi.add(txtKodeKurirTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 220, -1));
        pnlTransaksi.add(txtOngkosKirimTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 220, -1));

        btnCetakTransaksi.setText("CETAK");
        btnCetakTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakTransaksiActionPerformed(evt);
            }
        });
        pnlTransaksi.add(btnCetakTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, 100, -1));

        Content.add(pnlTransaksi, "card5");

        pnlKurir.setBackground(new java.awt.Color(204, 204, 204));
        pnlKurir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Ongkos Kirim");
        pnlKurir.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Kode Kurir");
        pnlKurir.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Nama Kurir");
        pnlKurir.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("ID Kurir");
        pnlKurir.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        pnlKurir.add(txtNamaKurir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 220, -1));
        pnlKurir.add(txtIdKurir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 220, -1));
        pnlKurir.add(txtOngkosKirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 220, -1));
        pnlKurir.add(txtKodeKurir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 220, -1));

        txtCariKurir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKurirKeyReleased(evt);
            }
        });
        pnlKurir.add(txtCariKurir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 370, -1));

        btnHpsKurir.setText("HAPUS");
        btnHpsKurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsKurirActionPerformed(evt);
            }
        });
        pnlKurir.add(btnHpsKurir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 90, -1));

        btnSmpnKurir.setText("SIMPAN");
        btnSmpnKurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnKurirActionPerformed(evt);
            }
        });
        pnlKurir.add(btnSmpnKurir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 90, -1));

        btnUbhKurir.setText("UBAH");
        btnUbhKurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhKurirActionPerformed(evt);
            }
        });
        pnlKurir.add(btnUbhKurir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 90, -1));

        tabelKurir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelKurir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKurirMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelKurir);

        pnlKurir.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 480, 220));

        btnCetakKurir.setText("CETAK");
        btnCetakKurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakKurirActionPerformed(evt);
            }
        });
        pnlKurir.add(btnCetakKurir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 90, -1));

        Content.add(pnlKurir, "card5");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        Header.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel1.setText("SISTEM INFORMASI PERIKANAN");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(283, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(153, 255, 255));

        btnToko.setBackground(new java.awt.Color(204, 255, 204));
        btnToko.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnToko.setForeground(new java.awt.Color(0, 0, 0));
        btnToko.setText("TOKO");
        btnToko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTokoActionPerformed(evt);
            }
        });

        btnTransaksi.setBackground(new java.awt.Color(204, 255, 204));
        btnTransaksi.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnTransaksi.setForeground(new java.awt.Color(0, 0, 0));
        btnTransaksi.setText("TRANSAKSI");
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });

        btnProduk.setBackground(new java.awt.Color(204, 255, 204));
        btnProduk.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnProduk.setForeground(new java.awt.Color(0, 0, 0));
        btnProduk.setText("PRODUK");
        btnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdukActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(204, 255, 204));
        btnHome.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnKurir.setBackground(new java.awt.Color(204, 255, 204));
        btnKurir.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnKurir.setForeground(new java.awt.Color(0, 0, 0));
        btnKurir.setText("KURIR");
        btnKurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKurirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToko, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduk)
                    .addComponent(btnTransaksi)
                    .addComponent(btnKurir))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnKurir, btnProduk, btnToko, btnTransaksi});

        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProduk)
                .addGap(18, 18, 18)
                .addComponent(btnToko, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKurir)
                .addGap(18, 18, 18)
                .addComponent(btnTransaksi)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnKurir, btnProduk, btnToko, btnTransaksi});

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnTokoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTokoActionPerformed
        Content.removeAll(); 
        Content.add(pnlToko);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnTokoActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        Content.removeAll(); 
        Content.add(pnlTransaksi);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdukActionPerformed
        Content.removeAll(); 
        Content.add(pnlProduk);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnProdukActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Content.removeAll(); 
        Content.add(pnlHome);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnKurirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurirActionPerformed
        Content.removeAll(); 
        Content.add(pnlKurir);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnKurirActionPerformed

    private void txtProdukRelasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdukRelasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdukRelasiActionPerformed

    private void btnSmpnTokoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnTokoActionPerformed
        try {
        if(txtIdToko.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "ID Toko Belum Diisi");
            txtIdToko.requestFocus();
        } else if(txtNamaToko.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Toko Belum Diisi");
            txtNamaToko.requestFocus();
        } else if(txtAlamatToko.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Alamat Toko Belum Diisi");
            txtAlamatToko.requestFocus();
        } else if(txtTlpToko.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "No Telp Toko Belum Diisi");
            txtTlpToko.requestFocus();
        } else if(txtRatingToko.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Rating Belum Diisi");
            txtRatingToko.requestFocus();
        } else if(txtProdukRelasi.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Produk Belum Diisi");
            txtProdukRelasi.requestFocus();
        
        } else {
            mycode.simpanToko02(txtIdToko.getText(), txtNamaToko.getText(),
                                txtAlamatToko.getText(), txtTlpToko.getText(),
                                txtRatingToko.getText(), txtProdukRelasi.getText());

            // Refresh tabel
            mycode.tampilDataToko(tabelToko, "SELECT*FROM toko");

            // Cek duplikasi
            if (mycode.duplikasi == true){
                txtNamaToko.setText(mycode.CEK_NAMA_TOKO);
                txtAlamatToko.setText(mycode.CEK_ALAMAT_TOKO);
                txtTlpToko.setText(mycode.CEK_NO_TLP_TOKO);
                txtRatingToko.setText(mycode.CEK_RATING);
                txtProdukRelasi.setText(mycode.CEK_PRODUK_TOKO);
               
            }
        }
    } catch (Exception e) {
    }
    }//GEN-LAST:event_btnSmpnTokoActionPerformed

    private void btnUbhTokoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhTokoActionPerformed
        try {
            mycode.ubahToko(txtIdToko.getText(), txtNamaToko.getText(),
                                txtAlamatToko.getText(), txtTlpToko.getText(),
                                txtRatingToko.getText(), txtProdukRelasi.getText()
                );

                // Refresh tabel
                mycode.tampilDataToko(tabelToko, "SELECT*FROM toko");
            } catch (Exception e) {
            }
    }//GEN-LAST:event_btnUbhTokoActionPerformed

    private void btnHpsTokoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsTokoActionPerformed
          try {
        mycode.hapusToko(txtIdToko.getText());
        mycode.tampilDataToko(tabelToko, "SELECT*FROM toko");
    } catch (Exception e) {
    }

    }//GEN-LAST:event_btnHpsTokoActionPerformed

    private void txtCariTokoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariTokoKeyReleased
      
    String c = txtCariToko.getText();
    String cari = "SELECT*FROM toko WHERE id_toko LIKE '%"+c+"%'"+
                  "OR nama_toko LIKE '%"+c+"%' OR alamat_toko LIKE '%"+c+"%'"+
                  "OR rating LIKE '%"+c+"%' OR produk LIKE '%"+c+"%'";
    mycode.tampilDataToko(tabelToko, cari);

    }//GEN-LAST:event_txtCariTokoKeyReleased

    private void btnUbhBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhBrgActionPerformed
           try {
        mycode.ubahTransaksi(txtIdTransaksi.getText(), txtInvoice.getText(),
                             txtTglBeli.getText(),
                             txtNamaTokoTrans.getText(), txtNamaProdukTrans.getText(),
                             txtHargaTrans.getText(), txtJlhProdukTrans.getText(),
                             txtTotalHarga.getText(), txtKodeKurirTrans.getText(),
                             txtOngkosKirimTrans.getText(), txtJlhTotal.getText());
        
        // Refresh tabel
        mycode.tampilDataTransaksi(tabelTransaksi, "SELECT*FROM transaksi");
    } catch (Exception e) {
    }

    }//GEN-LAST:event_btnUbhBrgActionPerformed

    private void btnSmpnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnTransaksiActionPerformed
         try {
        if(txtIdTransaksi.getText().isEmpty()){ 
            JOptionPane.showMessageDialog(null, "ID Belum Diisi");
            txtIdTransaksi.requestFocus();
        } else if(txtInvoice.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Invoice Belum Diisi");
            txtInvoice.requestFocus();
        } else if(txtTglBeli.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Tgl Beli Belum Diisi");
            txtTglBeli.requestFocus();
        } else if(txtNamaTokoTrans.getText().isEmpty()){ 
            JOptionPane.showMessageDialog(null, "Nama Toko Belum Diisi");
            txtNamaTokoTrans.requestFocus();
        } else if(txtNamaProdukTrans.getText().isEmpty()){ 
            JOptionPane.showMessageDialog(null, "Nama Produk Belum Diisi");
            txtNamaProdukTrans.requestFocus();
        } else if(txtHargaTrans.getText().isEmpty()){ 
            JOptionPane.showMessageDialog(null, "Harga Belum Diisi");
            txtHargaTrans.requestFocus();
        } else if(txtJlhProdukTrans.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Jumlah Produk Belum Diisi");
            txtJlhProdukTrans.requestFocus();
        } else if(txtTotalHarga.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Total Harga Belum Diisi");
            txtTotalHarga.requestFocus();
        } else if(txtKodeKurirTrans.getText().isEmpty()){ 
            JOptionPane.showMessageDialog(null, "Kode Kurir Belum Diisi");
            txtKodeKurirTrans.requestFocus();
        } else if(txtOngkosKirimTrans.getText().isEmpty()){ 
            JOptionPane.showMessageDialog(null, "Ongkos Kirim Belum Diisi");
            txtOngkosKirimTrans.requestFocus();
        } else if(txtJlhTotal.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Jumlah Total Belum Diisi");
            txtJlhTotal.requestFocus();
        } else {
            mycode.simpanTransaksi02(txtIdTransaksi.getText(), txtInvoice.getText(),
                                     txtTglBeli.getText(),
                                     txtNamaTokoTrans.getText(), txtNamaProdukTrans.getText(),
                                     txtHargaTrans.getText(), txtJlhProdukTrans.getText(),
                                     txtTotalHarga.getText(), txtKodeKurirTrans.getText(),
                                     txtOngkosKirimTrans.getText(), txtJlhTotal.getText());

            // Refresh tabel
            mycode.tampilDataTransaksi(tabelTransaksi, "SELECT*FROM transaksi");

            // Cek duplikasi
            if (mycode.duplikasi == true){
                txtInvoice.setText(mycode.CEK_INVOICE);
                txtTglBeli.setText(mycode.CEK_TGL_BELI);
                txtNamaTokoTrans.setText(mycode.CEK_NAMA_TOKO_TR);
                txtNamaProdukTrans.setText(mycode.CEK_NAMA_PRODUK_TR);
                txtHargaTrans.setText(mycode.CEK_HARGA_TR);
                txtJlhProdukTrans.setText(mycode.CEK_JLH_PRODUK);
                txtTotalHarga.setText(mycode.CEK_TOTAL_HARGA);
                txtKodeKurirTrans.setText(mycode.CEK_KODE_KURIR_TR);
                txtOngkosKirimTrans.setText(mycode.CEK_ONGKOS_KIRIM_TR);
                txtJlhTotal.setText(mycode.CEK_JLH_TOTAL);
            }
        }
    } catch (Exception e) {
    }

    }//GEN-LAST:event_btnSmpnTransaksiActionPerformed

    private void btnHpsTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsTransaksiActionPerformed
        try {
        mycode.hapusTransaksi(txtIdTransaksi.getText());
        mycode.tampilDataTransaksi(tabelTransaksi, "SELECT*FROM transaksi");
    } catch (Exception e) {
    }

    }//GEN-LAST:event_btnHpsTransaksiActionPerformed

    private void txtCariTransaksiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariTransaksiKeyReleased
        String c = txtCariTransaksi.getText();
        String cari = "SELECT*FROM transaksi WHERE id LIKE '%"+c+"%'"+
                      "OR invoice LIKE '%"+c+"%' OR tgl_beli LIKE '%"+c+"%'"+
                      "OR nama_toko LIKE '%"+c+"%'"+
                      "OR nama_produk LIKE '%"+c+"%' OR harga LIKE '%"+c+"%'"+
                      "OR jlh_produk LIKE '%"+c+"%' OR total_harga LIKE '%"+c+"%'"+
                      "OR kode_kurir LIKE '%"+c+"%' OR ongkos_kirim LIKE '%"+c+"%'"+
                      "OR jlh_total LIKE '%"+c+"%'";
        mycode.tampilDataTransaksi(tabelTransaksi, cari);
    }//GEN-LAST:event_txtCariTransaksiKeyReleased

    private void txtCariKurirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKurirKeyReleased
        String c = txtCariKurir.getText();
    String cari = "SELECT*FROM kurir WHERE id_kurir LIKE '%"+c+"%'"+
                  "OR nama_kurir LIKE '%"+c+"%' OR kode_kurir LIKE '%"+c+"%'"+
                  "OR ongkos_kirim LIKE '%"+c+"%'";
    mycode.tampilDataKurir(tabelKurir, cari);

    }//GEN-LAST:event_txtCariKurirKeyReleased

    private void btnHpsKurirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsKurirActionPerformed
        try {
        mycode.hapusKurir(txtIdKurir.getText());
        mycode.tampilDataKurir(tabelKurir, "SELECT*FROM kurir");
    } catch (Exception e) {
    }

    }//GEN-LAST:event_btnHpsKurirActionPerformed

    private void btnSmpnKurirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnKurirActionPerformed
        try {
        if(txtIdKurir.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "ID Kurir Belum Diisi");
            txtIdKurir.requestFocus();
        } else if(txtNamaKurir.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Kurir Belum Diisi");
            txtNamaKurir.requestFocus();
        } else if(txtKodeKurir.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Kode Kurir Belum Diisi");
            txtKodeKurir.requestFocus();
        } else if(txtOngkosKirim.getText().isEmpty()){ 
            JOptionPane.showMessageDialog(null, "Ongkos Kirim Belum Diisi");
            txtOngkosKirim.requestFocus();
        } else {
            mycode.simpanKurir02(txtIdKurir.getText(), txtNamaKurir.getText(),
                                 txtKodeKurir.getText(), txtOngkosKirim.getText());

            // Refresh tabel
            mycode.tampilDataKurir(tabelKurir, "SELECT*FROM kurir");

            // Cek duplikasi
            if (mycode.duplikasi == true){
                txtNamaKurir.setText(mycode.CEK_NAMA_KURIR);
                txtKodeKurir.setText(mycode.CEK_KODE_KURIR);
                txtOngkosKirim.setText(mycode.CEK_ONGKOS_KIRIM);
            }
        }
    } catch (Exception e) {
    }

    }//GEN-LAST:event_btnSmpnKurirActionPerformed

    private void btnUbhKurirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhKurirActionPerformed
        try {
        mycode.ubahKurir(txtIdKurir.getText(), txtNamaKurir.getText(),
                         txtKodeKurir.getText(), txtOngkosKirim.getText());
        
        // Refresh tabel
        mycode.tampilDataKurir(tabelKurir, "SELECT*FROM kurir");
    } catch (Exception e) {
    }

    }//GEN-LAST:event_btnUbhKurirActionPerformed

    private void btnHpsProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsProdukActionPerformed
      try {
        mycode.hapusProduk(txtIdProduk.getText());
        mycode.tampilDataProduk(tabelProduk, "SELECT*FROM produk");
    } catch (Exception e) {
    }

    }//GEN-LAST:event_btnHpsProdukActionPerformed

    private void btnSmpnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnProdukActionPerformed
        try {
        if(txtIdProduk.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "ID Belum Diisi");
            txtIdProduk.requestFocus();
        } else if(txtNamaProduk.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Produk Belum Diisi");
            txtNamaProduk.requestFocus();
        } else if(txtDeskripsi.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Deskripsi Belum Diisi");
            txtDeskripsi.requestFocus();
        } else if(txtKategori.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Kategori Belum Diisi");
            txtKategori.requestFocus();
        } else if(txtHrgProduk.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Harga Belum Diisi");
            txtHrgProduk.requestFocus();
        } else if(txtBerat.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Berat Belum Diisi");
            txtBerat.requestFocus();
        } else if(txtStok.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Stok Belum Diisi");
            txtStok.requestFocus();
        // Validasi txtGambarProduk DIHILANGKAN
        } else {
            mycode.simpanProduk02(txtIdProduk.getText(), txtNamaProduk.getText(),
                                  txtDeskripsi.getText(), txtKategori.getText(),
                                  txtHrgProduk.getText(), txtBerat.getText(),
                                  txtStok.getText());

            // Refresh tabel
            mycode.tampilDataProduk(tabelProduk, "SELECT*FROM produk");

            // Cek duplikasi
            if (mycode.duplikasi == true){
                txtNamaProduk.setText(mycode.CEK_NAMA_PRODUK);
                txtDeskripsi.setText(mycode.CEK_DESKRIPSI);
                txtKategori.setText(mycode.CEK_KATEGORI);
                txtHargaTrans.setText(mycode.CEK_HARGA);
                txtBerat.setText(mycode.CEK_BERAT);
                txtStok.setText(mycode.CEK_STOK);
                // Pengisian txtGambarProduk DIHILANGKAN
            }
        }
    } catch (Exception e) {
    }

    }//GEN-LAST:event_btnSmpnProdukActionPerformed

    private void btnUbhPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhPOActionPerformed
         try {
        mycode.ubahProduk(txtIdProduk.getText(), txtNamaProduk.getText(),
                          txtDeskripsi.getText(), txtKategori.getText(),
                          txtHargaTrans.getText(), txtBerat.getText(),
                          txtStok.getText());
        
        // Refresh tabel
        mycode.tampilDataProduk(tabelProduk, "SELECT*FROM produk");
    } catch (Exception e) {
    }

    }//GEN-LAST:event_btnUbhPOActionPerformed

    private void txtCariProdukKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariProdukKeyReleased
      String c = txtCariProduk.getText();
    // Pola 01 (Tidak Aman) sesuai contoh Anda
    String cari = "SELECT*FROM produk WHERE id LIKE '%"+c+"%'"+
                  "OR nama_produk LIKE '%"+c+"%' OR kategori LIKE '%"+c+"%'"+
                  "OR harga LIKE '%"+c+"%' OR stok LIKE '%"+c+"%'";
    mycode.tampilDataProduk(tabelProduk, cari);

    }//GEN-LAST:event_txtCariProdukKeyReleased

    private void btnCetakProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakProdukActionPerformed
        mycode.cetaklaporan("src/report/produk.jrxml", "SELECT * FROM produk"); 
    }//GEN-LAST:event_btnCetakProdukActionPerformed

    private void btnCetakTokoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakTokoActionPerformed
        mycode.cetaklaporan("src/report/toko.jrxml", "SELECT * FROM toko"); 
    }//GEN-LAST:event_btnCetakTokoActionPerformed

    private void btnCetakTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakTransaksiActionPerformed
        mycode.cetaklaporan("src/report/transaksi.jrxml", "SELECT * FROM transaksi"); 
    }//GEN-LAST:event_btnCetakTransaksiActionPerformed

    private void btnCetakKurirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakKurirActionPerformed
        mycode.cetaklaporan("src/report/kurir.jrxml", "SELECT * FROM kurir"); 
    }//GEN-LAST:event_btnCetakKurirActionPerformed

    private void tabelProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelProdukMouseClicked
        int baris = tabelProduk.getSelectedRow();
        txtIdProduk.setText(tabelProduk.getValueAt(baris, 0).toString());
        txtNamaProduk.setText(tabelProduk.getValueAt(baris, 1).toString());
        txtDeskripsi.setText(tabelProduk.getValueAt(baris, 2).toString());
        txtKategori.setText(tabelProduk.getValueAt(baris, 3).toString());
        txtHrgProduk.setText(tabelProduk.getValueAt(baris, 4).toString());
        txtBerat.setText(tabelProduk.getValueAt(baris, 5).toString());
        txtStok.setText(tabelProduk.getValueAt(baris, 6).toString());
    }//GEN-LAST:event_tabelProdukMouseClicked

    private void tabelTokoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTokoMouseClicked
        int baris = tabelToko.getSelectedRow();
        txtIdToko.setText(tabelToko.getValueAt(baris, 0).toString());
        txtNamaToko.setText(tabelToko.getValueAt(baris, 1).toString());
        txtAlamatToko.setText(tabelToko.getValueAt(baris, 2).toString());
        txtTlpToko.setText(tabelToko.getValueAt(baris, 3).toString());
        txtRatingToko.setText(tabelToko.getValueAt(baris, 4).toString());
        txtProdukRelasi.setText(tabelToko.getValueAt(baris, 5).toString());
    }//GEN-LAST:event_tabelTokoMouseClicked

    private void tabelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTransaksiMouseClicked
        int baris = tabelTransaksi.getSelectedRow();
        txtIdTransaksi.setText(tabelTransaksi.getValueAt(baris, 0).toString());
        txtInvoice.setText(tabelTransaksi.getValueAt(baris, 1).toString());
        txtTglBeli.setText(tabelTransaksi.getValueAt(baris, 2).toString());
        txtNamaTokoTrans.setText(tabelTransaksi.getValueAt(baris, 3).toString());
        txtNamaProdukTrans.setText(tabelTransaksi.getValueAt(baris, 4).toString());
        txtHargaTrans.setText(tabelTransaksi.getValueAt(baris, 5).toString());
        txtJlhProdukTrans.setText(tabelTransaksi.getValueAt(baris, 6).toString());
        txtTotalHarga.setText(tabelTransaksi.getValueAt(baris, 7).toString());
        txtKodeKurirTrans.setText(tabelTransaksi.getValueAt(baris, 8).toString());
        txtOngkosKirimTrans.setText(tabelTransaksi.getValueAt(baris, 9).toString());
        txtJlhTotal.setText(tabelTransaksi.getValueAt(baris, 10).toString());
    }//GEN-LAST:event_tabelTransaksiMouseClicked

    private void tabelKurirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKurirMouseClicked
        int baris = tabelKurir.getSelectedRow();
        txtIdKurir.setText(tabelKurir.getValueAt(baris, 0).toString());
        txtNamaKurir.setText(tabelKurir.getValueAt(baris, 1).toString());
        txtKodeKurir.setText(tabelKurir.getValueAt(baris, 2).toString());
        txtOngkosKirim.setText(tabelKurir.getValueAt(baris, 3).toString());
    }//GEN-LAST:event_tabelKurirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnCetakKurir;
    private javax.swing.JButton btnCetakProduk;
    private javax.swing.JButton btnCetakToko;
    private javax.swing.JButton btnCetakTransaksi;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHpsKurir;
    private javax.swing.JButton btnHpsProduk;
    private javax.swing.JButton btnHpsToko;
    private javax.swing.JButton btnHpsTransaksi;
    private javax.swing.JButton btnKurir;
    private javax.swing.JButton btnProduk;
    private javax.swing.JButton btnSmpnKurir;
    private javax.swing.JButton btnSmpnProduk;
    private javax.swing.JButton btnSmpnToko;
    private javax.swing.JButton btnSmpnTransaksi;
    private javax.swing.JButton btnToko;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JButton btnUbhBrg;
    private javax.swing.JButton btnUbhKurir;
    private javax.swing.JButton btnUbhPO;
    private javax.swing.JButton btnUbhToko;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlKurir;
    private javax.swing.JPanel pnlProduk;
    private javax.swing.JPanel pnlToko;
    private javax.swing.JPanel pnlTransaksi;
    private javax.swing.JTable tabelKurir;
    private javax.swing.JTable tabelProduk;
    private javax.swing.JTable tabelToko;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JTextField txtAlamatToko;
    private javax.swing.JTextField txtBerat;
    private javax.swing.JTextField txtCariKurir;
    private javax.swing.JTextField txtCariProduk;
    private javax.swing.JTextField txtCariToko;
    private javax.swing.JTextField txtCariTransaksi;
    private javax.swing.JTextField txtDeskripsi;
    private javax.swing.JTextField txtHargaTrans;
    private javax.swing.JTextField txtHrgProduk;
    private javax.swing.JTextField txtIdKurir;
    private javax.swing.JTextField txtIdProduk;
    private javax.swing.JTextField txtIdToko;
    private javax.swing.JTextField txtIdTransaksi;
    private javax.swing.JTextField txtInvoice;
    private javax.swing.JTextField txtJlhProdukTrans;
    private javax.swing.JTextField txtJlhTotal;
    private javax.swing.JTextField txtKategori;
    private javax.swing.JTextField txtKodeKurir;
    private javax.swing.JTextField txtKodeKurirTrans;
    private javax.swing.JTextField txtNamaKurir;
    private javax.swing.JTextField txtNamaProduk;
    private javax.swing.JTextField txtNamaProdukTrans;
    private javax.swing.JTextField txtNamaToko;
    private javax.swing.JTextField txtNamaTokoTrans;
    private javax.swing.JTextField txtOngkosKirim;
    private javax.swing.JTextField txtOngkosKirimTrans;
    private javax.swing.JTextField txtProdukRelasi;
    private javax.swing.JTextField txtRatingToko;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtTglBeli;
    private javax.swing.JTextField txtTlpToko;
    private javax.swing.JTextField txtTotalHarga;
    // End of variables declaration//GEN-END:variables
}
